### ISSUE TITLE
repository.yaml

### ISSUE THREAD

**Issue by frodef** [ThomDietrich/home-assistant-addons#13]
I'm unable to add this repository to my HA, and I suspect it's because there needs to be a repository.yaml ?

**Comment by ThomDietrich** [comment]
This should work:
Go to Settings -> Add-ons -> Add-on Store -> Menu "Repositories" -> Add `https://github.com/ThomDietrich/home-assistant-addons`

**Comment by frodef** [comment]
Thanks, I'd done that several times, restarted HA, and everything. Your repository still didn't show up. Turns out, it's a case of browser caching (even across HA restarts!) Refreshing the Add-on store page with CTRL-F5 did the trick. Seems to me to be a bug in HA core wrt. wrong cache policy. Sorry for the noise here.
