### ISSUE TITLE
AutoSSH installation fails

### ISSUE THREAD

**Issue by cnieves1** [ThomDietrich/home-assistant-addons#2]
Hi,
I have Home Assistant 2021.8.8 as a docker Raspbian managed by portainer.

I tried installing AutoSSH in HA. I added your repository to the addon store, then I selected it and clicked on install button, but it failed:
`  
Failed to to call /addons/5da1ffb2_autossh/install - The command '/bin/ash -o pipefail -c apk add --no-cache tzdata jq openssh vim curl autossh' returned a non-zero code: 3
`
Then I opened a terminal in portainer, and tried:
```
bash-5.1# apk add --no-cache tzdata jq openssh vim curl autossh
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz
(1/7) Installing autossh (1.4g-r1)
(2/7) Installing openssh-sftp-server (8.4_p1-r3)
(3/7) Installing openssh-server-common (8.4_p1-r3)
(4/7) Installing openssh-server (8.4_p1-r3)
(5/7) Installing openssh (8.4_p1-r3)
(6/7) Installing xxd (8.2.2320-r0)
(7/7) Installing vim (8.2.2320-r0)
Executing busybox-1.32.1-r6.trigger
OK: 146 MiB in 187 packages
bash-5.1# 
```
It seems it works, but not using the install button. Do you know what can I do to fix this?

Thanks in advance,

**Comment by ThomDietrich** [comment]
Hey, did you ever solve this? I'm a bit clueless myself

**Comment by cnieves1** [comment]
No, I couldn't... So I switched to HA OS which is easier to manage (at least for me)...
