### ISSUE TITLE
Error "s6-overlay-suexec: fatal: can only run as pid 1"

### ISSUE THREAD

**Issue by systemiii** [ThomDietrich/home-assistant-addons#5]
I have installed the addon on Home assistant Core 2022.5.4 and when i start It i see error "s6-overlay-suexec: fatal: can only run as pid 1" in log

**Comment by ThomDietrich** [comment]
Could reproduce.
Discussed here: https://community.home-assistant.io/t/hello-world-example-addon-from-developer-docs-stopped-working-s6-overlay-issue/421486/9

**Comment by ThomDietrich** [comment]
Seems to be working again :)

**Comment by systemiii** [comment]
Wow, your addon Is very good and you are the fastest fixer.
I confirm now It works.
Thank you
