### ISSUE TITLE
Channel 0: connection failed: Operation timed out

### ISSUE THREAD

**Issue by matthieup240** [ThomDietrich/home-assistant-addons#9]
After updating Home Assistant to the 2022.12, the reverse proxy can't established a connection...
Here is the logs : 
`connect_to 172.17.0.1 port 8443: failed.
debug1: channel 0: free: 192.168.16.2, nchannels 7
debug1: channel 1: connection failed: Operation timed out`

I didn't change anything in my configuration before and after the HA update.
Do you have an idea ?

**Comment by matthieup240** [comment]
I found the problem, The docker ip address has been changed during the last release
172.17.0.1 -> 172.17.232.1

**Comment by ThomDietrich** [comment]
Fixed via https://github.com/ThomDietrich/home-assistant-addons/pull/11
